### ISSUE TITLE
惩罚游戏转盘和翻牌历史重叠

### ISSUE THREAD

**Issue by MikasaAckerman** [MatChat-Inc/UsenGame-HighAndLow#3]
惩罚游戏选择的是随机前提，
1. 游戏页面点击绿色按钮进入惩罚游戏转盘
2. 转一下开始停止
3. 再转一下开始停止
4. 按蓝色按钮「他のルーレットに変更する」
5. 按蓝色按钮「編集」
6. 按蓝色按钮「保存してこのルーレットで遊ぶ」

最后如图，
![Image](https://github.com/user-attachments/assets/c93eb471-54e9-4b78-901c-ef430f797f2c)
![Image](https://github.com/user-attachments/assets/332b6161-baed-468f-b047-81bf90528c78)

补充视频：

https://github.com/user-attachments/assets/a7f6bc28-1681-49ec-9630-aa5690d5c926

**Comment by 949886** [comment]
这个 bug 好像以前就出现过，而且是只有电视上才会出现的bug。
以前是因为喵喵的架构和我那个不太一样，他是在gameobject上在套了层单独的类，所以把 gameobject 设置了 inactive 后 事件还是会继续响应。
我试了下电脑上还是复现不了。这次的原因可能要复杂些。

**Comment by 949886** [comment]
解决。原因是点「他のルーレットに変更する」会退出当前转盘直接跳到别的页面，导致直接判断转盘退出了，High&Low的逻辑就会执行了，所以再按蓝色按钮就会显示历史。

现在改成了每一帧都会判断是否显示了惩罚游戏。
